### PR TITLE
Use latest Akka verison

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg What do you think, shall we bounce up all versions? This will force the server to be run on Java 8+ JVMs

**Comment by nsg** [comment]
@petterarvidsson for release 10? sure.

**Comment by petterarvidsson** [comment]
yes, for 10.

**Comment by petterarvidsson** [comment]
@nsg I will release this as 0.2.0 and then make PRs for all plugins to use this version (as well as Java 8)

**Pull request merged**
