### PR TITLE
Feature add support for block type classes

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This adds support for a block type to have a list of class IDs related to it. I am thinking generic stuff like "Wood", "Planks" or "Burnable". I will also add support so that crafting recipes can use classes directly. So that something that requires planks to build can use any type that has the class "Planks". Think it will be pretty useful to get this set up before we add too many blocks.

**Comment by petterarvidsson** [comment]
@nsg I have now rewritten some parts of the konstructing system and it now works also with block classes, i.e. a konstructing pattern can contain the class "Wood" rather than a specific block type id. I still need to update the server, but I think this part is more or less done now. I have taken the freedom to not keep the changes to the obscure konstructing system backwards compatible. There are no known users except the server and the existing code was a bit vague.

**Comment by nsg** [comment]
@petterarvidsson cool! This will be really useful. I haven't looked at the code/examples yet but I agree that there are no problem to break comparability in this case.

**Comment by petterarvidsson** [comment]
Added some docs and fixed some typos. I am happy, Travis is happy, everyone is happy :smile: so I'll merge now and make a new API relase and fix https://github.com/konstructs/server/pull/121 to use it!

**Pull request merged**
