### PR TITLE
Feature extend api with rotation

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This extends the API with what is required for putting blocks in any possible orientation. It is required by https://github.com/konstructs/server/pull/134 and therefore needs to be merged before it can be finalized (if it is published as a snapshot locally, the server pull works with it).

**Comment by nsg** [comment]
> - Add bool "orientable" to BockType that decides if a block may be

A typo

**Comment by nsg** [comment]
Nice! Looks really good! :+1:

**Comment by petterarvidsson** [comment]
@nsg Fixed missing documentation, will go ahead and merge now.

**Pull request merged**
